version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.2-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Setup dependencies
          command: |
            gem install bundler:2.1.4
            bundle install --without production --path=${BUNDLE_PATH:-vendor/bundle}
            bundle exec rake db:create db:migrate
#      - ruby/bundle-install
      - run:
          name: Run backend tests
          command:
            bundle exec rspec spec
