version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/ruby:2.6.2-stretch-node
      environment:
        BUNDLE_JOBS: 3
        BUNDLE_RETRY: 3
        PGHOST: 127.0.0.1
        PGUSER: postgres
        RAILS_ENV: test
    - image: circleci/postgres:11.3-alpine
      environment:
        POSTGRES_USER: postgres
        POSTGRES_DB: announcement_test
        POSTGRES_PASSWORD: ""

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Setup dependencies
          command: |
            gem install bundler:2.1.4
            bundle install --without production --path=${BUNDLE_PATH:-vendor/bundle}
            bundle exec rake db:create db:migrate
#      - ruby/bundle-install
      - run:
          name: Run backend tests
          command:
            bundle exec rspec spec
